apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-router
  namespace: kube-router
  labels:
    k8s-app: kube-router
spec:
  selector:
    matchLabels:
      k8s-app: kube-router
  template:
    metadata:
      labels:
        k8s-app: kube-router
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: kube-router
      hostNetwork: true
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      containers:
        - name: kube-router
          image: docker.io/cloudnativelabs/kube-router:v2.3.0
          args:
            - --run-router=false
            - --run-firewall=true
            - --run-service-proxy=false
          securityContext:
            privileged: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              memory: 256Mi
