apiVersion: v1
kind: Service
metadata:
  name: pickpro-notifications
  namespace: pickpro
  labels:
    app: pickpro-notifications
spec:
  type: ClusterIP
  selector:
    app: pickpro-notifications
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http