apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prospectio-pgvector-pvc
  namespace: prospectio
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-prospectio-pgvector
  resources:
    requests:
      storage: 5Gi