apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: pickpro
data:
  config.yml: |
    tunnel: 7d240cf1-d600-40c4-9d6f-72f1ebce26a7

    originRequest:
      noTLSVerify: true
      keepAliveTimeout: 30s
      connectTimeout: 30s
      tcpKeepAlive: 10s
      keepAliveConnections: 100

    ingress:

      - hostname: pickpro.io
        service: http://traefik.kube-system.svc.cluster.local:80
        
      - hostname: app.pickpro.io
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: api.pickpro.io
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: indexing-api.pickpro.io
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: oauth2-proxy.pickpro.io
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: "*.pickpro.io"
        service: http://traefik.kube-system.svc.cluster.local:80

      - service: http_status:404