apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencode-data
  namespace: opencode
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-opencode-opencode
  resources:
    requests:
      storage: 5Gi