apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-soludev-openobserve
  namespace: soludev
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-soludev-openobserve
  nfs:
    server: 37.60.225.137
    path: /srv/nfs/soludev/openobserve
  mountOptions:
    - hard
    - nfsvers=4
    - timeo=300
    - retrans=10
    - rsize=1048576
    - wsize=1048576
    - noatime
    - nodiratime
