apiVersion: v1
kind: ConfigMap
metadata:
  name: pickpro-front-config
  namespace: pickpro
data:
  config.json: |
    {
        "backendUrl": "https://api.pickpro.io",
        "oauth2ProxyUrl": "https://app.pickpro.io",
        "logtoUrl": "https://logto.soludev.tech",
        "logtoAppId": "sazp1vx8ah3pwv56rqm9v",
        "cvExtractionTimeoutMs": 120000,
        "useMock": false,
        "devMode": false
    }
