apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: soludev
  labels:
    app: valkey
spec:
  type: ClusterIP
  selector:
    app: valkey
  ports:
    - name: valkey
      port: 6379
      targetPort: 6379
      protocol: TCP