apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valkey
  namespace: soludev
spec:
  volumeName: nfs-soludev-valkey
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-soludev-valkey
  resources:
    requests:
      storage: 1Gi