apiVersion: apps/v1
kind: Deployment
metadata:
  name: pickpro-api
  namespace: pickpro-dev
  labels:
    app: pickpro-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pickpro-api
  template:
    metadata:
      labels:
        app: pickpro-api
        app.kubernetes.io/part-of: soludev-workload
    spec:
      containers:
        - name: pickpro-api
          image: kaiohz/pickpro:pickpro-back-c97f7eaf23820c9cc315f3e97960c941c0a198f0
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: pickpro-api-config
            - secretRef:
                name: pickpro-api-secret
          livenessProbe:
            httpGet:
              path: /pickpro/rest/v1/health
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /pickpro/rest/v1/health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 5
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "3Gi"
              cpu: "2000m"
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      imagePullSecrets:
        - name: pickpro-docker-secret