apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pickpro-docker-external-secret
  namespace: pickpro-dev
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: pickpro-docker-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfigjson }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: pickpro-dev/docker
        property: .dockerconfigjson