apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-soludev-openobserve
  namespace: soludev
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-soludev-openobserve
  nfs:
    server: 100.64.0.3
    path: /Volumes/NFSStorage/soludev/openobserve
  mountOptions:
    - nfsvers=3
    - soft
    - timeo=100
    - retrans=3
    - actimeo=10
    - rsize=1048576
    - wsize=1048576
    - noatime
    - nodiratime
