apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-ubby-pgvector
  namespace: ubby
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-ubby-pgvector
  nfs:
    server: 37.60.225.137
    path: /srv/nfs/ubby/pgvector
  mountOptions:
    - hard
    - nfsvers=4
    - timeo=600
    - retrans=10
    - rsize=1048576
    - wsize=1048576
    - noatime
    - nodiratime
