apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-external-secret
  namespace: pickpro-dev
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: minio-pickpro
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: pickpro-dev/minio