# MinIO PickPro DEV — stockage local sur Storage30
# Data: /srv/nfs/pickpro-dev/minio
# Secret: pickpro-dev/minio (openbao)
# Install helm manuel : helm upgrade --install minio-pickpro-dev minio/minio -n pickpro-dev -f config/prd/minio/pickpro/values.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-external-secret
  namespace: pickpro-dev
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: minio-pickpro
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: pickpro-dev/minio
