apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: moltbot
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-moltbot-minio
  resources:
    requests:
      storage: 5Gi
