apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unispace-back-external-secret
  namespace: unispace
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: unispace-back-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: unispace/back
