apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nats-external-secret
  namespace: soludev
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: nats-auth
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: soludev/nats