apiVersion: v1
kind: ConfigMap
metadata:
  name: ubby-front-config
  namespace: ubby
data:
  config.json: |
    {
      "apiBaseUrl": "https://ubby-back.soludev.tech/api/v1",
      "supabaseUrl": "https://cxjiiggphuhqgmqvjgcw.supabase.co",
      "supabasePublishableKey": "sb_publishable_0A7hw0HI6aREf11jS7bk8w_-OCxQB1U"
    }