apiVersion: v1
kind: Service
metadata:
  name: raganything
  namespace: composables
spec:
  selector:
    app: raganything
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP