apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-dev-sonarqube
  namespace: soludev
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-dev-sonarqube
  nfs:
    server: 100.64.0.3
    path: /Volumes/NFSStorage/dev/sonarqube
  mountOptions:
    - hard
    - nfsvers=3
    - timeo=600
    - retrans=10
    - rsize=1048576
    - wsize=1048576
    - noatime
    - nodiratime