apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-sonarqube
  namespace: soludev
spec:
  volumeName: local-sonarqube
  accessModes:
    - ReadWriteOnce
  storageClassName: local-sonarqube
  resources:
    requests:
      storage: 5Gi