apiVersion: v1
kind: ConfigMap
metadata:
  name: composable-ui-config
  namespace: composables
data:
  config.json: |
    {
      "apiBaseUrl": "https://composables-agent.soludev.tech",
      "wsBaseUrl": "wss://composables-agent.soludev.tech",
      "ragApiBaseUrl": "https://raganything.soludev.tech"
    }