apiVersion: apps/v1
kind: Deployment
metadata:
  name: pickpro-api
  namespace: pickpro
  labels:
    app: pickpro-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pickpro-api
  template:
    metadata:
      labels:
        app: pickpro-api
        app.kubernetes.io/part-of: soludev-workload
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/part-of: soludev-workload
      containers:
        - name: pickpro-api
          image: kaiohz/pickpro:pickpro-back-be9176980db973b73a2a05a71d5f4cb73d5a2735
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: pickpro-api-config
            - secretRef:
                name: pickpro-api-secret
          livenessProbe:
            httpGet:
              path: /pickpro/rest/v1/health
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /pickpro/rest/v1/health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "800m"
            limits:
              memory: "1024Mi"
              cpu: "1000mi"
      imagePullSecrets:
        - name: pickpro-docker-secret
