apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: composable-ui-external-secret
  namespace: composables
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: composable-ui-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: composables/composable-ui