apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: soludev
data:
  config.yml: |
    tunnel: a67e25e7-bae5-4a2d-a46e-fc05d0c1f84e

    originRequest:
      noTLSVerify: true
      keepAliveTimeout: 30s
      connectTimeout: 30s
      tcpKeepAlive: 10s
      keepAliveConnections: 100

    ingress:

      - hostname: soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: bao.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: logto.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: logto-admin.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: phoenix.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: headlamp.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: ubby.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: ubby-back.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: ubby-mcp-api.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: ubby-oauth2-proxy.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: openclaw.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: hooks-openclaw.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: liame.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: unispace.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: unispace-back.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: opencode.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: opencode-oauth2-proxy.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: nats.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80

      - hostname: "*.soludev.tech"
        service: http://traefik.kube-system.svc.cluster.local:80

      - service: http_status:404