# MinIO de Composables — stockage local direct sur Storage30 (déplacé du NFS)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: composables-minio-pvc
  namespace: composables
spec:
  volumeName: local-composables-minio
  accessModes:
    - ReadWriteOnce
  storageClassName: local-composables-minio
  resources:
    requests:
      storage: 5Gi
