apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-soludev-telemetry-postgres
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-soludev-telemetry-postgres
  nfs:
    server: 100.64.0.5
    path: /srv/nfs/soludev/postgres
  mountOptions:
    - hard
    - nfsvers=4
    - timeo=600
    - retrans=10
    - rsize=1048576
    - wsize=1048576
    - noatime
    - nodiratime
