apiVersion: v1
kind: Service
metadata:
  name: postgres-telemetry
  namespace: soludev
  labels:
    app: postgres-telemetry
spec:
  selector:
    app: postgres-telemetry
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
