apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soludev-telemetry-pg-pvc
  namespace: soludev
spec:
  volumeName: nfs-soludev-telemetry-postgres
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-soludev-telemetry-postgres
  resources:
    requests:
      storage: 20Gi
