apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: soludev
spec:
  volumeName: nfs-soludev-minio
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-soludev-minio
  resources:
    requests:
      storage: 10Gi
