apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: soludev
spec:
  volumeName: nfs-dev-minio-soludev
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-dev-minio-soludev
  resources:
    requests:
      storage: 10Gi