apiVersion: v1
kind: Service
metadata:
  name: liame-landing
  namespace: liame
  labels:
    app: liam-landing
spec:
  type: ClusterIP
  selector:
    app: liame-landing
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
