apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: composables
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      tolerations:
        - key: "klipperlb-exclude"
          value: "true"
          effect: "NoSchedule"
          operator: "Equal"
      imagePullSecrets:
        - name: pickpro-docker-secret
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: composables-postgres-pvc
      containers:
        - name: postgres
          image: kaiohz/pickpro:postgres-raganything-a39cb399bc6027bf950d347f02ff55f9a1b76149
          imagePullPolicy: Always
          args: ["postgres", "-c", "shared_preload_libraries=pg_textsearch"]
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "composable_agents", "-d", "composable_agents"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"
