apiVersion: apps/v1
kind: Deployment
metadata:
  name: pickpro-indexing-api
  namespace: pickpro
  labels:
    app: pickpro-indexing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pickpro-indexing-api
  template:
    metadata:
      labels:
        app: pickpro-indexing-api
        app.kubernetes.io/part-of: soludev-workload
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/part-of: soludev-workload
      containers:
        - name: pickpro-indexing-api
          image: kaiohz/pickpro:pickpro-indexing-api-88edc64ccd0fe521d382b097429c518ef3c97156
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: pickpro-indexing-api-config
            - secretRef:
                name: pickpro-indexing-api-secret
          livenessProbe:
            httpGet:
              path: /pickpro/rest/v1/health/status
              port: 8000
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /pickpro/rest/v1/health/status
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
      imagePullSecrets:
        - name: pickpro-docker-secret
