apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclaw-data
  namespace: openclaw
spec:
  accessModes:
    - ReadWriteMany
  volumeName: nfs-openclaw
  resources:
    requests:
      storage: 5Gi