apiVersion: apps/v1
kind: Deployment
metadata:
  name: soludev-landing
  namespace: soludev
  labels:
    app: soludev-landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soludev-landing
  template:
    metadata:
      labels:
        app: soludev-landing
        app.kubernetes.io/part-of: soludev-workload
    spec:
      tolerations:
        - key: "klipperlb-exclude"
          value: "true"
          effect: "NoSchedule"
          operator: "Equal"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/part-of: soludev-workload
      containers:
        - name: soludev-landing
          image: kaiohz/soludev-landing:6f280ece2aa3f0bfc5c227f9acbfa725bcbbe0e8
          ports:
            - containerPort: 80
          env:
            - name: OPENOBSERVE_ENABLED
              value: "true"
            - name: OPENOBSERVE_SITE
              value: "openobserve.soludev.tech"
            - name: OPENOBSERVE_CLIENT_TOKEN
              value: "rumWf3mnqgZHLkSPfQr"
            - name: OPENOBSERVE_ORG_ID
              value: "default"
            - name: OPENOBSERVE_APPLICATION_ID
              value: "soludev-landing"
            - name: OPENOBSERVE_SERVICE
              value: "soludev-landing"
            - name: OPENOBSERVE_VERSION
              value: "0.1.0"
            - name: CLARITY_ENABLED
              value: "true"
            - name: CLARITY_PROJECT_ID
              value: "y1iyt6knib"
            - name: AHREFS_ENABLED
              value: "true"
            - name: AHREFS_KEY
              value: "3cn1WFDnk2VUKpFzqCFdHw"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "96Mi"
              cpu: "100m"
