apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unispace-postgres-pvc
  namespace: unispace
spec:
  volumeName: nfs-unispace-postgres
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-unispace-postgres
  resources:
    requests:
      storage: 5Gi
