apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-kustomization
  namespace: flux-system
spec:
  interval: 2m
  timeout: 90s
  wait: false
  sourceRef:
    kind: GitRepository
    name: kaiohz-repo
  path: "dev/cluster"
  prune: false
