apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-soludev
  namespace: flux-system
spec:
  interval: 2m
  timeout: 90s
  wait: true
  targetNamespace: soludev
  sourceRef:
    kind: GitRepository
    name: kaiohz-repo
  path: "dev/soludev"
  prune: true
