apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pickpro-minio
  namespace: pickpro
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-pickpro-minio
  nfs:
    server: 100.64.0.5
    path: /srv/nfs/pickpro/minio
  mountOptions:
    - hard
    - nfsvers=4
    - timeo=300
    - retrans=10
    - rsize=1048576
    - wsize=1048576
    - noatime
    - nodiratime
