apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: soludev
data:
  config.yml: |
    tunnel: 7b69fce6-d4ee-4cc4-a9c1-a644cb5096d3

    originRequest:
      noTLSVerify: true
      keepAliveTimeout: 30s
      connectTimeout: 30s
      tcpKeepAlive: 10s
      keepAliveConnections: 100

    ingress:
      - hostname: forgejo.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: logto-dev.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: logto-dev-admin.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: pickpro.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: pickpro-api.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: pickpro-indexing-api.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: pickpro-oauth2-proxy.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: sonarqube.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: openobserve.soludev.tech
        service: http://traefik.kube-system.svc.cluster.local:80
      - service: http_status:404
