apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencode-data
  namespace: soludev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path