apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: soludev
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        app.kubernetes.io/part-of: soludev-workload
    spec:
      tolerations:
        - key: "klipperlb-exclude"
          value: "true"
          effect: "NoSchedule"
          operator: "Equal"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/part-of: soludev-workload
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: soludev-pgvector-pvc
      containers:
        - name: postgres
          image: postgres:17-alpine
          securityContext:
            runAsUser: 70
            runAsGroup: 70
          args: ["-c", "max_connections=500", "-c", "shared_buffers=128MB", "-c", "tcp_keepalives_idle=30", "-c", "tcp_keepalives_interval=10", "-c", "tcp_keepalives_count=6", "-c", "idle_in_transaction_session_timeout=60000", "-c", "effective_io_concurrency=0", "-c", "wal_sync_method=fdatasync", "-c", "max_wal_size=2GB", "-c", "min_wal_size=512MB", "-c", "checkpoint_completion_target=0.9", "-c", "wal_buffers=16MB", "-c", "checkpoint_flush_after=0", "-c", "bgwriter_lru_maxpages=1000", "-c", "bgwriter_delay=200ms"]
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          startupProbe:
            tcpSocket:
              port: 5432
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
