apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-dev-postgres
  namespace: soludev
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-dev-postgres
  nfs:
    server: 100.64.0.5
    path: /Volumes/NFSStorage/dev/postgres
  mountOptions:
    - hard
    - nfsvers=4
    - timeo=600
    - retrans=10
    - rsize=1048576
    - wsize=1048576
    - noatime
    - nodiratime
