apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-soludev-postgres
  namespace: soludev
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-soludev-postgres
  nfs:
    server: 37.60.225.137
    path: /srv/nfs/soludev/postgres
  mountOptions:
    - nfsvers=3
    - soft
    - timeo=300
    - retrans=10
    - actimeo=60
    - rsize=1048576
    - wsize=1048576
    - noatime
    - nodiratime
