apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-postgres-pvc
  namespace: soludev
spec:
  volumeName: nfs-dev-postgres
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-dev-postgres
  resources:
    requests:
      storage: 5Gi
