apiVersion: apps/v1
kind: Deployment
metadata:
  name: pickpro-indexing-api
  namespace: pickpro
  labels:
    app: pickpro-indexing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pickpro-indexing-api
  template:
    metadata:
      labels:
        app: pickpro-indexing-api
    spec:
      containers:
        - name: pickpro-indexing-api
          image: kaiohz/pickpro:pickpro-indexing-api-7f7a899eb1dd62a6233091f225c1720451cc0a96
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: pickpro-indexing-api-config
            - secretRef:
                name: pickpro-indexing-api-secret
          livenessProbe:
            httpGet:
              path: /pickpro/rest/v1/health/status
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /pickpro/rest/v1/health/status
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: pickpro-docker-secret
