apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pickpro-pgvector-pvc
  namespace: pickpro
spec:
  volumeName: nfs-dev-pickpro-pgvector
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-dev-pickpro-pgvector
  resources:
    requests:
      storage: 5Gi