apiVersion: v1
kind: Service
metadata:
  name: pickpro-front
  namespace: pickpro-dev
  labels:
    app: pickpro-front
spec:
  type: ClusterIP
  selector:
    app: pickpro-front
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http