apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logto-ingress-main
  namespace: soludev
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/redirect-scheme: https
    traefik.ingress.kubernetes.io/router.priority: "10"  # Priorité basse

spec:
  rules:
    - host: dev-logto.soludev.tech
      http:
        paths:
          - path: /core
            pathType: Prefix
            backend:
              service:
                name: logto
                port:
                  number: 3001